/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ipos.view.sales;

import com.ipos.entity.Item;
import com.ipos.entity.Sales;
import com.ipos.entity.Stock;
import com.ipos.helper.util.DateUtil;
import com.ipos.helper.util.DecimalFormatterUtil;
import com.ipos.helper.util.JComboBoxModelUtil;
import com.ipos.jpa.controller.ItemJpaController;
import com.ipos.jpa.controller.SalesJpaController;
import com.ipos.jpa.controller.StockJpaController;
import com.ipos.jpa.controller.SupplierJpaController;
import com.ipos.jpa.controller.UnitJpaController;
import com.ipos.start.IPOS;
import java.math.BigDecimal;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author megeh
 */
public class AcceptPaymentDialog extends javax.swing.JDialog {

    private SalesJpaController controller;
    private StockJpaController stockJpaController;
    private SupplierJpaController supplierJpaController;
    private ItemJpaController itemJpaController;
    private UnitJpaController unitJpaController;
    private DecimalFormatterUtil dfNoComma;
    private DecimalFormatterUtil dfWithComma;
    private Stock stock;
    private BigDecimal unitPrice;
    private BigDecimal quantity;
    private BigDecimal total;

    /**
     * Creates new form StockInDialog
     *
     * @param parent
     * @param modal
     * @param emf
     */
    public AcceptPaymentDialog(java.awt.Frame parent, boolean modal, EntityManagerFactory emf) {
        super(parent, modal);
        initComponents();
        initElements(emf);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        centerPanel = new javax.swing.JPanel();
        bottomSeparator = new javax.swing.JSeparator();
        itemComboBox = new javax.swing.JComboBox();
        itemLabel = new javax.swing.JLabel();
        stocksLabel = new javax.swing.JLabel();
        stockValueLabel = new javax.swing.JLabel();
        unitPriceLabel = new javax.swing.JLabel();
        unitPriceValueLabel = new javax.swing.JLabel();
        quantityFormattedTextField = new javax.swing.JFormattedTextField();
        quantityLabel = new javax.swing.JLabel();
        cashLabel = new javax.swing.JLabel();
        cashFormattedTextField = new javax.swing.JFormattedTextField();
        bottomSeparator1 = new javax.swing.JSeparator();
        posAmountsPanel = new javax.swing.JPanel();
        posLeftPanel = new javax.swing.JPanel();
        totalLabel = new javax.swing.JLabel();
        totalValueLabel = new javax.swing.JLabel();
        posCenterPanel = new javax.swing.JPanel();
        posRightPanel = new javax.swing.JPanel();
        changeLabel = new javax.swing.JLabel();
        changeValueLabel = new javax.swing.JLabel();
        unitLabel = new javax.swing.JLabel();
        bottomPanel = new javax.swing.JPanel();
        acceptButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stock In");

        mainPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        mainPanel.add(topPanel, java.awt.BorderLayout.NORTH);

        itemComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        itemComboBox.setName("approvedBy"); // NOI18N
        itemComboBox.setPreferredSize(new java.awt.Dimension(205, 27));
        itemComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemComboBoxActionPerformed(evt);
            }
        });

        itemLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemLabel.setText("Item");

        stocksLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stocksLabel.setText("Stocks");

        stockValueLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stockValueLabel.setForeground(new java.awt.Color(255, 0, 0));
        stockValueLabel.setText("-- NA --");

        unitPriceLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        unitPriceLabel.setText("Unit Price");

        unitPriceValueLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        unitPriceValueLabel.setForeground(new java.awt.Color(255, 0, 0));
        unitPriceValueLabel.setText("-- NA --");

        quantityFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        quantityFormattedTextField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        quantityFormattedTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        quantityFormattedTextField.setName("assetValue"); // NOI18N
        quantityFormattedTextField.setPreferredSize(new java.awt.Dimension(6, 27));
        quantityFormattedTextField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                quantityFormattedTextFieldCaretUpdate(evt);
            }
        });

        quantityLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        quantityLabel.setText("Quantity");

        cashLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cashLabel.setText("Cash");

        cashFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        cashFormattedTextField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        cashFormattedTextField.setText("0.00");
        cashFormattedTextField.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        cashFormattedTextField.setName("assetValue"); // NOI18N
        cashFormattedTextField.setPreferredSize(new java.awt.Dimension(6, 27));
        cashFormattedTextField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                cashFormattedTextFieldCaretUpdate(evt);
            }
        });

        posAmountsPanel.setLayout(new java.awt.BorderLayout());

        posLeftPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        posLeftPanel.setPreferredSize(new java.awt.Dimension(290, 0));

        totalLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalLabel.setText("TOTAL");

        totalValueLabel.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        totalValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        totalValueLabel.setText("0.00");

        javax.swing.GroupLayout posLeftPanelLayout = new javax.swing.GroupLayout(posLeftPanel);
        posLeftPanel.setLayout(posLeftPanelLayout);
        posLeftPanelLayout.setHorizontalGroup(
            posLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(posLeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(posLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
                .addContainerGap())
        );
        posLeftPanelLayout.setVerticalGroup(
            posLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(posLeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addContainerGap())
        );

        posAmountsPanel.add(posLeftPanel, java.awt.BorderLayout.WEST);

        javax.swing.GroupLayout posCenterPanelLayout = new javax.swing.GroupLayout(posCenterPanel);
        posCenterPanel.setLayout(posCenterPanelLayout);
        posCenterPanelLayout.setHorizontalGroup(
            posCenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        posCenterPanelLayout.setVerticalGroup(
            posCenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 103, Short.MAX_VALUE)
        );

        posAmountsPanel.add(posCenterPanel, java.awt.BorderLayout.CENTER);

        posRightPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        posRightPanel.setPreferredSize(new java.awt.Dimension(290, 0));

        changeLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        changeLabel.setForeground(new java.awt.Color(255, 0, 0));
        changeLabel.setText("CHANGE");

        changeValueLabel.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        changeValueLabel.setForeground(new java.awt.Color(255, 0, 0));
        changeValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        changeValueLabel.setText("0.00");

        javax.swing.GroupLayout posRightPanelLayout = new javax.swing.GroupLayout(posRightPanel);
        posRightPanel.setLayout(posRightPanelLayout);
        posRightPanelLayout.setHorizontalGroup(
            posRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(posRightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(posRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(changeValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
                .addContainerGap())
        );
        posRightPanelLayout.setVerticalGroup(
            posRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(posRightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(changeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changeValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addContainerGap())
        );

        posAmountsPanel.add(posRightPanel, java.awt.BorderLayout.EAST);

        unitLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        unitLabel.setForeground(new java.awt.Color(255, 0, 0));
        unitLabel.setText("-- unit --");

        javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bottomSeparator, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(bottomSeparator1)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addComponent(posAmountsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(centerPanelLayout.createSequentialGroup()
                                .addComponent(itemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(itemComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(centerPanelLayout.createSequentialGroup()
                                .addComponent(stocksLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stockValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addComponent(unitPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unitPriceValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(centerPanelLayout.createSequentialGroup()
                                .addComponent(quantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quantityFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(unitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(centerPanelLayout.createSequentialGroup()
                                .addComponent(cashLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cashFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stocksLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stockValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unitPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unitPriceValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityLabel)
                    .addComponent(quantityFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cashLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cashFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(bottomSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(posAmountsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(bottomSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainPanel.add(centerPanel, java.awt.BorderLayout.CENTER);

        bottomPanel.setPreferredSize(new java.awt.Dimension(400, 50));

        acceptButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        acceptButton.setText("ACCEPT");
        acceptButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cancelButton.setText("CANCEL");
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomPanelLayout.createSequentialGroup()
                .addContainerGap(384, Short.MAX_VALUE)
                .addComponent(acceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(acceptButton, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        mainPanel.add(bottomPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        Sales entity = new Sales();

        try {
            // Check if it has unit and supplier selected.
            if (itemComboBox.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Error, please select item.", "Failed", JOptionPane.ERROR_MESSAGE);

                return;
            }

            entity.setQuantity(dfNoComma.format(quantityFormattedTextField.getText()));
            entity.setUnitPrice(unitPrice);
            entity.setCashAmount(dfNoComma.format(cashFormattedTextField.getText()));
            entity.setChangeAmount(dfNoComma.format(changeValueLabel.getText()));
            entity.setTotalAmount(total);
            entity.setDate(DateUtil.current());
            entity.setFKstockId(stock.getId());
            entity.setFKcreatedByUserId(IPOS.currentUser.getId());

            controller.create(entity);

            // Update stock on quantity withdrawn.
            stock.setQuantity(stock.getQuantity().subtract(entity.getQuantity()));

            stockJpaController.edit(stock);

            JOptionPane.showMessageDialog(null, "Sales successfully saved.", "Sucess", JOptionPane.INFORMATION_MESSAGE);

            hideThis();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error, sales not saved.", "Failed", JOptionPane.ERROR_MESSAGE);

            Logger.getLogger(AcceptPaymentDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_acceptButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        hideThis();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void itemComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemComboBoxActionPerformed
        Item item = (Item) itemComboBox.getSelectedItem();
        List<Stock> stocks = stockJpaController.findStock(item);

        if (!stocks.isEmpty()) {
            stock = stocks.get(0);
            unitPrice = stock.getUnitPrice();
            quantity = stock.getQuantity();

            // Set stock details.
            stockValueLabel.setText(dfWithComma.format(stock.getQuantity()));
            unitPriceValueLabel.setText(dfWithComma.format(unitPrice));
            quantityFormattedTextField.setText(dfNoComma.format(quantity));
            unitLabel.setText(unitJpaController.findUnit(item.getFKunitId()).getDescription());

            calculateTotal();
        }
    }//GEN-LAST:event_itemComboBoxActionPerformed

    private void quantityFormattedTextFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_quantityFormattedTextFieldCaretUpdate
        calculateTotal();
    }//GEN-LAST:event_quantityFormattedTextFieldCaretUpdate

    private void cashFormattedTextFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_cashFormattedTextFieldCaretUpdate
        calculateTotal();
    }//GEN-LAST:event_cashFormattedTextFieldCaretUpdate

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JSeparator bottomSeparator;
    private javax.swing.JSeparator bottomSeparator1;
    private javax.swing.JButton cancelButton;
    public javax.swing.JFormattedTextField cashFormattedTextField;
    private javax.swing.JLabel cashLabel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel changeLabel;
    private javax.swing.JLabel changeValueLabel;
    private javax.swing.JComboBox itemComboBox;
    private javax.swing.JLabel itemLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel posAmountsPanel;
    private javax.swing.JPanel posCenterPanel;
    private javax.swing.JPanel posLeftPanel;
    private javax.swing.JPanel posRightPanel;
    public javax.swing.JFormattedTextField quantityFormattedTextField;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JLabel stockValueLabel;
    private javax.swing.JLabel stocksLabel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel totalValueLabel;
    private javax.swing.JLabel unitLabel;
    private javax.swing.JLabel unitPriceLabel;
    private javax.swing.JLabel unitPriceValueLabel;
    // End of variables declaration//GEN-END:variables

    private void initElements(EntityManagerFactory emf) {
        controller = new SalesJpaController(emf);
        stockJpaController = new StockJpaController(emf);
        supplierJpaController = new SupplierJpaController(emf);
        itemJpaController = new ItemJpaController(emf);
        unitJpaController = new UnitJpaController(emf);
        dfNoComma = new DecimalFormatterUtil("#####0.00");
        dfWithComma = new DecimalFormatterUtil();
        unitPrice = BigDecimal.ZERO;
        quantity = BigDecimal.ZERO;

        // Set combo box.
        itemComboBox.setModel(JComboBoxModelUtil.getItemModel("Select Item", itemJpaController.findItemEntities()));
    }

    private void hideThis() {
        this.setVisible(false);
    }

    private void calculateTotal() {
        String q = (quantityFormattedTextField.getText().isEmpty() ? "0.00" : quantityFormattedTextField.getText());
        String c = (cashFormattedTextField.getText().isEmpty() ? "0.00" : cashFormattedTextField.getText());

        total = unitPrice.multiply(dfNoComma.format(q));

        totalValueLabel.setText(dfWithComma.format(total));

        // Calculate change.
        changeValueLabel.setText(dfWithComma.format(total.subtract(dfNoComma.format(c))));
    }
}
